name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Docker-Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Setup Docker-Compose
      run: docker-compose up -d
    - name: Create migrations
      run: python manage.py makemigrations
    - name: Aply migrations
      run: python manage.py migrate
    - name: Run Tests
      run: docker exec backend sh -c "flake8 . && pytest ."
